name: Docker Image CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and export
      uses: docker/build-push-action@v2
      with:
        context: .
        load: true
        tags: ${{ github.repository }}:test

    - name: Run image
      run: docker run --rm --privileged --detach --name test $GITHUB_REPOSITORY:test

    - name: Wait for dockerd
      run: for i in {1..10}; do sleep 1; [[ -S /var/run/docker.sock ]] && break || false; done
      shell: bash --noprofile --norc -o pipefail {0}

    - name: Test image
      run: docker exec --tty test docker info

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: ${{ github.repository }}:latest
